hosts:
   -  hostname: 3.232.239.122
      sid: S4H
      number: 00
      port: 50001
      credentials: abapci_user
      role: development
      repo_id: i079666gcts1

   -  hostname: 18.212.25.230
      sid: S4H
      number: 00
      port: 50001
      credentials: abapci_user
      role: test
      repo_id: i079666gcts1     
